name: "Publish Apps"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Ninja Setup
        if: runner.os == 'Linux'
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
         channel: "stable"
      - name: Install deps
        run: flutter pub get
      - name: Build Android App
        if: runner.os == 'Linux'
        run: flutter build apk
      - name: Build iOS App
        if: runner.os == 'macOS'
        run: flutter build ios
      - name: Build Windows App
        if: runner.os == 'Windows'
        run: flutter build windows
      - name: Build Linux App
        if: runner.os == 'Linux'
        run: flutter build linux